---

- hosts: mbmsgw224
  gather_facts: false

  tasks:

#CIQ
#sm range: ff3e::8000:0/116
#m1-1 network: fd00:2600:2600:105::/64
#m1-1 gateway 1: fd00:2600:2600:105::3
#m1-1 gateway 2: fd00:2600:2600:105::4

    - name: context m1 config
      cli_command:
        command: '{{ item }}'

      with_items:
      - config
      - contexts context m1
      - router bfd interface if-m1-1@m1
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bfd interface if-m1-2@m1
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router pim address-family ipv6 ssm range ff3e::8000:0/116
      - router pim address-family ipv6 interface if-m1-1@m1
      - sparse-mode
      - bfd true
      - router pim address-family ipv6 interface if-m1-2@m1
      - sparse-mode
      - bfd true
      - qos-protocol arp
      - priority ef
      - ipv6 static-route fd00:2600:2600:105::/64 next-hop-address fd00:2600:2600:105::3
      - bfd strict
      - ipv6 static-route fd00:2600:2600:105::/64 next-hop-address fd00:2600:2600:105::4
      - bfd strict
      - commit
      - exit

    - name: let's wait to commit and exit
      pause:
        seconds: 30

    - name: context m1 running-config
      cli_command:
        command: show running-config contexts context m1
      register: result

    - debug: var=result.stdout_lines
#CIQ
#sm-bgp-id: 64904
#sm bgp remote as: 65065
#bgp-router-id: 107.124.250.27
#sm neighbor1: 107.243.35.129
#sm neighbor2: 107.243.35.130
#sm neighbor3: 107.243.35.145
#sm neighbor4: 107.243.35.146


    - name: context sm config
      cli_command:
        command: '{{ item }}'

      with_items:
      - config
      - contexts context sm
      - router bfd interface if-sm-1@sm
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bfd interface if-sm-2@sm
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bgp 64904
      - router-id        107.124.224.27
      - graceful-restart false
      - address-family ipv4 unicast redistribute epg
      - address-family ipv6 unicast redistribute epg
      - neighbor 107.243.232.1
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sm-1@sm
      - remote-as              65065
      - address-family ipv4 unicast
      - neighbor 107.243.232.2
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sm-1@sm
      - remote-as              65065
      - address-family ipv4 unicast
      - neighbor 107.243.232.17
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sm-2@sm
      - remote-as              65065
      - address-family ipv4 unicast
      - neighbor 107.243.232.18
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sm-2@sm
      - remote-as              65065
      - address-family ipv4 unicast
      - commit
      - exit

    - name: let's wait to commit and exit
      pause:
        seconds: 30

    - name: context sm running-config
      cli_command:
        command: show running-config contexts context sm
      register: result

    - debug: var=result.stdout_lines


#CIQ
#sgimb-bgp-id: 64903
#sgimb bgp remote as: 65065
#bgp-router-id: 107.124.250.27
#sgimb neighbor1: fd00:c000:100:220::1
#sgimb neighbor2: fd00:c000:100:220::2
#sgimb neighbor3: fd00:c000:100:221::1
#sgimb neighbor4: fd00:c000:100:221::2


    - name: context sgimb config
      cli_command:
        command: '{{ item }}'

      with_items:
      - config
      - contexts context sgimb
      - router bfd interface if-sgimb-1@sgimb
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bfd interface if-sgimb-2@sgimb
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bgp 64903
      - router-id        107.124.224.27
      - graceful-restart false
#      - address-family ipv4 unicast flap-statistics
#      - address-family ipv4 unicast dampening route-map map-sgimb-1
#      - address-family ipv4 unicast redistribute epg
#      - address-family ipv6 unicast dampening route-map map-sgimb-1
      - address-family ipv6 unicast redistribute epg
#      - neighbor 107.243.233.1
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          1
#      - update-source interface if-sgimb-1@sgimb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgimb-1
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgimb-1
#      - neighbor 107.243.233.2
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgimb-1@sgimb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgimb-1
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgimb-1
#      - neighbor 107.243.233.17
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgimb-2@sgimb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgimb-2
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgimb-2
#      - neighbor 107.243.233.18
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgimb-2@sgimb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgimb-2
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgimb-2

      - neighbor fd00:c000:100:b80::1
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgimb-1@sgimb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgimb-1
      - neighbor fd00:c000:100:b80::2
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgimb-1@sgimb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgimb-1
      - neighbor fd00:c000:100:b81::1
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgimb-2@sgimb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgimb-2
      - neighbor fd00:c000:100:b81::2
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgimb-2@sgimb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgimb-2
#      - ipv6 static-route fd00:c000:100:b80::/64 next-hop-address fd00:c000:100:b80::1
#      - route-map map-sgimb-1
#      - seq 1
#      - seq-choice permit
#      - set ipv6 next-hop fd00:c000:100:b80::3
#      - match ipv6 address
#      - prefix-list any
#      - route-map map-sgimb-2
#      - seq 1
#      - seq-choice permit
#      - set ipv6 next-hop fd00:c000:100:b81::3
#      - match ipv6 address
#      - prefix-list any
      - commit
      - exit

    - name: let's wait to commit and exit
      pause:
        seconds: 30

    - name: context sgimb running-config
      cli_command:
        command: show running-config contexts context sgimb
      register: result

    - debug: var=result.stdout_lines
#CIQ
#sgmb-bgp-id: 64903
#sgmb bgp remote as: 65065
#bgp-router-id: 107.124.250.27
#sgmb neighbor1: fd00:c000:100:223::1
#sgmb neighbor2: fd00:c000:100:223::2
#sgmb neighbor3: fd00:c000:100:224::1
#sgmb neighbor4: fd00:c000:100:224::2

    - name: context sgmb config
      cli_command:
        command: '{{ item }}'

      with_items:
      - config
      - contexts context sgmb
      - router bfd interface if-sgmb-1@sgmb
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3
      - router bfd interface if-sgmb-2@sgmb
      - minimum transmit-interval 300
      - minimum receive-interval 300
      - detection-multiplier 3

      - router bgp 64903
      - router-id        107.124.224.27
      - graceful-restart false
#      - address-family ipv4 unicast redistribute epg
      - address-family ipv6 unicast redistribute epg

#      - neighbor 107.243.233.49
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgmb-1@sgmb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgmb-1
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgmb-1
#      - neighbor 107.243.233.50
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgmb-1@sgmb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgmb-1
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgmb-1
#      - neighbor 107.243.233.65
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgmb-2@sgmb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgmb-2
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgmb-2
#      - neighbor 107.243.233.66
#      - choice                 external
#      - advertisement-interval 0
#      - bfd
#      - ebgp-multihop          3
#      - update-source interface if-sgmb-2@sgmb
#      - remote-as              65065
#      - address-family ipv4 unicast route-map out
#      - map-set map-sgmb-2
#      - address-family ipv6 unicast route-map out
#      - map-set map-sgmb-2

      - neighbor fd00:c000:100:b83::1
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgmb-1@sgmb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgmb-1
      - neighbor fd00:c000:100:b83::2
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgmb-1@sgmb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#     - map-set map-sgmb-1
      - neighbor fd00:c000:100:b84::1
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgmb-2@sgmb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgmb-2
      - neighbor fd00:c000:100:b84::2
      - choice                 external
      - advertisement-interval 0
      - bfd
      - ebgp-multihop          3
      - update-source interface if-sgmb-2@sgmb
      - remote-as              65065
      - address-family ipv6 unicast #route-map out
#      - map-set map-sgmb-2
#      - route-map map-sgmb-1
#      - seq 1
#      - seq-choice permit
#      - set ipv6 next-hop fd00:c000:100:b83::3
#      - match ipv6 address
#      - prefix-list any
#      - route-map map-sgmb-2
#      - seq 1
#      - seq-choice permit
#      - set ipv6 next-hop fd00:c000:100:b84::3
#      - match ipv6 address
#      - prefix-list any
      - commit
      - exit

    - name: let's wait to commit and exit
      pause:
        seconds: 30

    - name: context sgmb running-config
      cli_command:
        command: show running-config contexts context sgmb
      register: result

    - debug: var=result.stdout_lines

