---

- hosts: zrdm52afmgw01
  gather_facts: false

  vars_files:
    - zrdm52afmgw01_enc.var

  tasks:

    - name: applications config
      cli_command:
        command: '{{ item }}'

      loop:
        - config
        - epg mbmsgw node {{epg_name}}
        - epg mbmsgw interface sm logical-interface sm
        - epg mbmsgw interface sm t3-response-time 4
        - epg mbmsgw interface sm n3-requests 2
        - epg mbmsgw interface sm diffserv {{sm_diffserv}}
        - epg mbmsgw interface sm echo-interval 60
        - epg mbmsgw interface sgmb diameter-application-system embms
        - epg mbmsgw interface sgimb logical-interface sgimb
        - epg mbmsgw interface sgimb udp-port-range range-start 1024
        - epg mbmsgw interface sgimb udp-port-range range-end 65535
        - epg mbmsgw interface m1 logical-interface m1
        - epg mbmsgw interface m1 diffserv {{m1_diffserv}}
        - epg mbmsgw interface m1 ssm-ipv6-address {{ssm_range}}
        - epg mbmsgw mme-list {{mme_list1}} 
        - address {{list1_mme20}}
        - address {{list1_mme09}}
        - epg mbmsgw mme-list {{mme_list2}}
        - address {{list2_mme18}}
        - epg mbmsgw mme-list {{mme_list3}}
        - address {{list3_mme19}}
        - epg mbmsgw mme-list {{mme_list4}}
        - address {{list4_dsTestMME}}
        - epg node board-allocation gc-0/3/1
        - epg node board-allocation gc-0/4/1
        - epg node board-allocation gu-0/1/1
        - epg node board-allocation gu-0/2/1
        - epg node diameter local-realm {{local_dia_realm}}
        - epg node diameter local-host-name {{local_dia_name}}
        - > 
          epg node diameter remote-diameter-peer {{peer_dia_name1}} 
          address {{peer_dia_ip1}}
          logical-interface sgmb 
          port 3869 
          watchdog 6
        - >
          epg node diameter remote-diameter-peer {{peer_dia_name2}}
          address {{peer_dia_ip2}} 
          logical-interface sgmb
          port 3869 
          watchdog 6
        - >
          epg node diameter diameter-application-system embms
          destination-realm {{dest_dia_realm}} 
          application-id sgmb
          peer bmsc-1 
          priority 0 
        - >
          epg node diameter diameter-application-system embms
          destination-realm {{dest_dia_realm}}
          application-id sgmb
          peer bmsc-2
          priority 1
        - >
          epg node logical-interface m1
          routing-instance m1
          ipv6-address     {{m1_epg_vip}}
        - >
          epg node logical-interface sgimb
          routing-instance sgimb
          ipv6-address     {{sgimb_epg_vip}}
        - >
          epg node logical-interface sgmb
          routing-instance sgmb
          ipv6-address     {{sgmb_epg_vip}}
        - >
          epg node logical-interface sm
          routing-instance sm
          address          {{sm_epg_vip}}
        - top
        - show configuration
        - commit check
        - commit
        - exit


    - name: let's wait to commit and exit
      pause:
        seconds: 30

    - name:  applications running-config
      cli_command:
        command: '{{ item }}'
      register: result

      loop:
        - show running-config epg mbmsgw node
        - show running-config epg mbmsgw interface sm
        - show running-config epg mbmsgw interface sgmb
        - show running-config epg mbmsgw interface sgimb
        - show running-config epg mbmsgw interface m1
        - show running-config epg mbmsgw mme-list
        - show running-config epg node board-allocation
        - show running-config epg node diameter
        - show running-config epg node logical-interface
    - debug: var=result.results[0].stdout_lines
    - debug: var=result.results[1].stdout_lines
    - debug: var=result.results[2].stdout_lines
    - debug: var=result.results[3].stdout_lines
    - debug: var=result.results[4].stdout_lines
    - debug: var=result.results[5].stdout_lines
    - debug: var=result.results[6].stdout_lines
    - debug: var=result.results[7].stdout_lines
    - debug: var=result.results[8].stdout_lines
