---

- hosts: mdfcp
  gather_facts: false
  become: yes

  vars_files:
    - zrdm52afbms01_enc.var

  tasks:
     - name: restart service ip6tables
       service:
         name: ip6tables
         state: restarted
