---

- hosts: mdf
  gather_facts: false
  become: yes

  vars_files:
    - zrdm52afbms01_enc.var

  tasks:

      - name: auth sufficient
        lineinfile:
          path: /etc/pam.d/password-auth
          insertafter: '^auth.*null.*pass'
          line: 'auth sufficient pam_ldap.so try_first_pass ignore_unknown_user ignore_authinfo_unavail'

      - name: account sufficient
        lineinfile:
          path: /etc/pam.d/password-auth
          insertafter: '^account.*pam_localuser.so'
          line: 'account     sufficient    pam_ldap.so ignore_unknown_user ignore_authinfo_unavail'

      - name: session required
        lineinfile:
          path: /etc/pam.d/password-auth
          insertafter: '^session.*revoke'
          line: 'session     required      pam_mkhomedir.so skel=/etc/skel umask=0022'

      - name: lines inserted
        shell: egrep '^auth.*null.*pass|^account.*pam_localuser.so|^session.*revoke' -A 1 /etc/pam.d/password-auth 
        register: result

      - debug: var=result.stdout_lines
