---

- hosts: os
  become: yes
  gather_facts: true

  vars_files:
    - zrdm52afbms01_enc.var

  tasks:

    - name: Back up diameter-config.xml
      copy:
        src: /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
        remote_src: yes
        dest: /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml.{{ansible_date_time.iso8601_basic_short}}
        owner: mdfcp
        group: bmsc
        mode: '0640'

    - name: test
      shell: '{{ item }}'

      loop:
        - sed -i '/DiameterUri/s/>.*</>aaa:\/\/{{SGmbDiameterUri}}:3869;transport=tcp</' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
        - sed -i '/OriginRealm/s/>.*</>{{SGmbOriginRealm}}</' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
        - sed -i '/HostIp/s/>.*</>{{SGmbDiaHostIP}}</' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
        - sed -i '/SgmbIp/s/>.*</>{{SGmbGWDiaIP}}</' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
        - sed -i '/SgmbHost/s/>.*</>{{SGmbGWDiaHost}}</' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml


    - name: show added line
      shell: egrep 'DiameterUri|OriginRealm|HostIp|SgmbIp|SgmbHost' /opt/ericsson/bm-sc/mdf-cp/default/conf/diameter-config.xml
      register: result

    - debug: var=result.stdout_lines

