---

- hosts: mdf
  become: yes

  vars_files:
    - zrdm52afbms01_enc.var

  tasks:

    - name: Back up snmpd.conf
      copy:
        src: /etc/snmp/snmpd.conf
        dest: /etc/snmp/snmpd.conf.{{ansible_date_time.iso8601_basic_short}}
        owner: root
        group: root
        mode: '0600'

    - shell: ls -al /etc/snmp/snmpd.conf*
      register: result
    - debug: var=result.stdout_lines

    - name: config snmpd
      blockinfile:
        insertafter: "lines are configuration commands"
        path: /etc/snmp/snmpd.conf
        block: |
          rocommunity redhat
          agentAddress udp:58161

    - shell: grep rocommunity /etc/snmp/snmpd.conf -A 2 -B 2
      register: result
    - debug: var=result.stdout_lines 

    - name: exclude .1.3.6.1.2.1.1 
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^view\s+systemview.*2.1.1'
        line: '#view    systemview    included   .1.3.6.1.2.1.1'

    - name: exclude .1.3.6.1.2.1.25.1.1
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^view\s+systemview.*5.1.1'
        line: '#view    systemview    included   .1.3.6.1.2.1.25.1.1'

    - shell: egrep '^#view\s+systemview' /etc/snmp/snmpd.conf
      register: result
    - debug: var=result.stdout_lines
